# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: dev_mmo
  password:
  host:
  port:

development:
  <<: *default
  database: dev_mmo_development


test:
  <<: *default
  database: dev_mmo_test

production:
  <<: *default
  database: dev_mmo_production
